if: branch = dev
language: bash
services:
  - docker

before_script:
  - cd ./docker
  - ./docker-login.sh
  - source ./common.sh

script:
  - ./build.sh
  - ./deploy.sh

after_script:
  - ./cleanup.sh
